services:
    pritunl:
        container_name: pritunl
        image: ghcr.io/jippi/docker-pritunl
        restart: unless-stopped
        privileged: true
        networks:
            - dokploy-network
        environment:
            - PRITUNL_MONGODB_URI=mongodb://pritunl:wf4agh6jklyerkow2406@services-pritunl-xjz6jw:27017/pritunl
        volumes:
            - './data/pritunl.conf:/etc/pritunl.conf'
            - './data/pritunl:/var/lib/pritunl'
  networks:
  dokploy-network:
    external: true
